---
title: "Untitled"
output: html_document
date: "2024-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preparation

### Remove old data

```{r}
rm(list=ls())
```

### Set the file direction

```{r}
setwd('/Users/qiushifeng/Desktop/macrocycle/summary')
getwd()
```

### Import data

```{r}
data <- read.csv(file = 'data0404_cp.csv', header = T, as.is = T, dec = ".", na.strings = ".")
```
### Summary

```{r}
summary(data[["Molecular_Weight"]])
summary(data[["Num_H_Acceptors"]])
summary(data[["Num_H_Donors"]])
summary(data[["cLogP"]])
summary(data[["TPSA"]])
summary(data[["Macrocycle_Ring_Size"]])
summary(data[["Macrocycle_Overall_Amide_Ratio"]])
summary(data[["Kier_index"]])






```



```{r}
# Load the data
data <- read.csv(file = 'data0404_cp.csv', header = TRUE, as.is = TRUE, dec = ".", na.strings = ".")

# Calculate counts based on specified conditions
count_Molecular_Weight_over_500 <- sum(data$Molecular_Weight > 500, na.rm = TRUE)
count_Num_H_Acceptors_over_10 <- sum(data$Num_H_Acceptors > 10, na.rm = TRUE)
count_Num_H_Donors_over_5 <- sum(data$Num_H_Donors > 5, na.rm = TRUE)
count_cLogP_over_5 <- sum(data$cLogP > 5, na.rm = TRUE)
count_TPSA_over_140 <- sum(data$TPSA > 140, na.rm = TRUE)
count_nrot <- sum(data$Num_Rotatable_Bonds > 10, na.rm = TRUE)

# Print the results
cat("Compounds with Molecular Weight > 500:", count_Molecular_Weight_over_500, "\n")
cat("Compounds with Num_H_Acceptors > 10:", count_Num_H_Acceptors_over_10, "\n")
cat("Compounds with Num_H_Donors > 5:", count_Num_H_Donors_over_5, "\n")
cat("Compounds with cLogP > 5:", count_cLogP_over_5, "\n")
cat("Compounds with TPSA > 140:", count_TPSA_over_140, "\n")
cat("Compounds with nRotB > 10:", count_nrot, "\n")

```


```{r}
# Calculate counts based on specified conditions
data <- read.csv(file = 'data0404_cp.csv', header = TRUE, as.is = TRUE, dec = ".", na.strings = ".")
# Define the filter condition
bRo5_data <- data[data$Molecular_Weight > 500 & (
    (data$Molecular_Weight >= 700 & data$Molecular_Weight <= 3000) |
    data$cLogP < 0 |
    data$cLogP > 7.5 |
    data$Num_H_Donors > 5 |
    data$Num_H_Acceptors > 10 |
    data$TPSA > 200 |
    data$Num_Rotatable_Bonds > 20
), ]


```

