---
title: "Untitled"
output: html_document
date: "2024-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preparation

### Remove old data

```{r}
rm(list=ls())
```

### Set the file direction

```{r}
setwd('/Users/qiushifeng/Desktop/macrocycle')
getwd()
```

### Import data

```{r}
data <- read.csv(file = '/Users/qiushifeng/Desktop/macrocycle/macrocycles_overall_sta.csv', header = T, as.is = T, dec = ".", na.strings = ".")
```

```{r}
data_features <- data[,3:10]
```

### Make Violin Plot for Both App and Eff dataset

```{r}
# Load the necessary libraries
library(ggplot2)
library(gridExtra)  # or library(patchwork) if you prefer


plots <- list()

# Define the y-axis limits for each plot
y_limits <- list(c(240, 1800), c(0, 30), c(0, 20), c(-5, 12), c(0, 40), 
                 c(0, 1000), c(10, 40), c(0, 0.8), c(0, 40))

for (i in 1:ncol(data_features)) {
    current_feature <- names(data_features)[i]
    
    p <- ggplot(data_features, aes_string(x = "''", y = current_feature)) +
        geom_boxplot(draw_quantiles = c(0.25, 0.5, 0.75)) +
        #geom_point(position = position_jitter(width = 0.1), size = 1, alpha = 0.5) +  # Adding points
        labs(title = current_feature, y = "", x = "") +
        theme_minimal() +
        theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), legend.position = "none")

    # Set y-axis limits
    if (i <= length(y_limits)) {
        p <- p + ylim(y_limits[[i]][1], y_limits[[i]][2])
    }
    
    plots[[i]] <- p
}
```



```{r}
# Load the necessary libraries
library(ggplot2)
library(gridExtra)  # or library(patchwork) if you prefer


plots <- list()

# Define the y-axis limits for each plot
y_limits <- list(c(240, 1800), c(0, 30), c(0, 20), c(-5, 12), c(0, 40), 
                 c(0, 1000), c(10, 40), c(0, 0.8), c(0, 40))

for (i in 1:ncol(data_features)) {
    current_feature <- names(data_features)[i]
    
    p <- ggplot(data_features, aes_string(x = "''", y = current_feature)) +
        geom_boxplot(draw_quantiles = c(0.25, 0.5, 0.75)) +
        #geom_point(position = position_jitter(width = 0.1), size = 1, alpha = 0.5) +  # Adding points
        labs(title = current_feature, y = "", x = "") +
        theme_minimal() +
        theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), legend.position = "none")

    # Set y-axis limits
    if (i <= length(y_limits)) {
        p <- p + ylim(y_limits[[i]][1], y_limits[[i]][2])
    }
    
    plots[[i]] <- p
}


# Combine the plots into a single row
combined_plot <- do.call(grid.arrange, c(plots, ncol = 5, 
                                         top = "Feature Distribution Dataset"))
ggsave("Feature_pe.png", plot = combined_plot, width = 8
      , height = 8, dpi = 600)
print("combined_plot")
```


```{r}
# Load the necessary libraries
library(ggplot2)
library(gridExtra)  # or library(patchwork) if you prefer

plots <- list()

# Define the y-axis limits for each plot
y_limits <- list(c(240, 1800), c(0, 30), c(0, 20), c(-5, 12), c(0, 40), 
                 c(0, 1000), c(10, 40), c(0, 0.8), c(0, 40))

# Create a vector of colors
colors <- grDevices::rainbow(length(y_limits))

for (i in 1:ncol(data_features)) {
    current_feature <- names(data_features)[i]
    
    p <- ggplot(data_features, aes_string(x = "''", y = current_feature)) +
        geom_boxplot(draw_quantiles = c(0.25, 0.5, 0.75), fill = colors[i]) + # Assign color here
        labs(title = current_feature, y = "", x = "") +
        theme_minimal() +
        theme(axis.text.x = element_blank(), 
              axis.ticks.x = element_blank(), 
              legend.position = "none",
              plot.title = element_text(size = 16),
              axis.text.y = element_text(size = 14)) # Increase size of y-axis text here

    # Set y-axis limits
    if (i <= length(y_limits)) {
        p <- p + ylim(y_limits[[i]][1], y_limits[[i]][2])
    }
    
    plots[[i]] <- p
}

# Combine the plots into a single row
combined_plot <- do.call(grid.arrange, c(plots, ncol = 5, 
                                         top = "Feature Distribution Dataset"))
ggsave("Feature_pe.png", plot = combined_plot, width = 8, height = 8, dpi = 600)
print("combined_plot")



```

```{r}
# Load the necessary libraries
library(ggplot2)
library(gridExtra)  # You can also use library(patchwork) for a different approach to combining plots

# Assuming data_features is your dataset

plots <- list()

# Create a vector of colors, one for each feature


for (i in 1:8) {  # Assuming you have 9 features you're interested in
    current_feature <- names(data_features)[i]
    
    p <- ggplot(data_features, aes_string(x = current_feature)) +
        geom_histogram(fill = "royalblue", bins = 30, color = "black") + # Adjust number of bins as necessary
        labs(title = current_feature) +
        theme_minimal() +
        theme(legend.position = "none",
              plot.title = element_text(size = 0.1),
              axis.title.x = element_text(size = 20),
              axis.title.y= element_text(size = 0.1),
              axis.text.x = element_text(size = 18, hjust = 1), 
              axis.text.y = element_text(size = 20),
              panel.border = element_rect(colour = "black", fill=NA, size=1))

    plots[[i]] <- p
}

# Combine the plots into a single layout
combined_plot <- do.call(grid.arrange, c(plots, ncol = 4, top = ""))
ggsave("Feature_histograms_combined_20.png", plot = combined_plot, width = 16, height = 8, dpi = 600)

```



```{r}
# Combine the plots into a single row
combined_plot <- do.call(grid.arrange, c(plots, ncol = 5, 
                                         top = "Feature Distribution Dataset"))
ggsave("Feature_pe.png", plot = combined_plot, width = 8
      , height = 8, dpi = 600)
print("combined_plot")
```




```{r}
library("FactoMineR")
library('factoextra')
data.pca <- PCA(data_features, graph = FALSE)
```

```{r}
eig.val <- get_eigenvalue(data.pca)
eig.val
fviz_eig(data.pca, title = "",
         addlabels = TRUE, ylim = c(0, 60))
```

```{r}
fviz_pca_var(data.pca, 
             title = "PCA Loading Plots of Papp and Pe Dataset, PC1 vs PC2",
             xlab = 'PC1 (53.8%)', ylab='PC2(17.8%)',
             col.var = "Grey",
             labelsize = 3
             )
```

```{r}
fviz_pca_ind(data.pca,
             title = "PCA Score Plot of Papp Dataset vs Pe Dataset, PC1 vs PC2",
             xlab = 'PC1 (50.6%)', ylab='PC2(23.7%)',
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = data_all$Set, # color by groups
             palette = c("#00AFBB", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )

```

```{r}
fviz_pca_var(data.pca, 
            axes = c(1, 3), # specify PC1 and PC3
             title = "PCA Loading Plots of Papp and Pe Dataset, PC1 vs PC3",
             xlab = 'PC1 (50.6%)', ylab='PC3 (10.1%)',
             col.var = "Purple",
             labelsize = 3)
```

```{r}
fviz_pca_ind(data.pca,
             axes = c(1, 3), # specify PC1 and PC3
             title = "PCA Score Plot of Papp Dataset vs Pe Dataset, PC1 vs PC3",
             xlab = 'PC1 (50.6%)', ylab='PC3 (10.1%)', # Update labels with appropriate percentages
             geom.ind = "point", # show points only (not "text")
             col.ind = data_all$Set, # color by groups
             palette = c("#00AFBB", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )

```

### Biplot for individuals (NOT NECESSARY)

```{r fig.width=20, fig.height=12}
#fviz_pca_biplot(data.pca, repel = TRUE,
#                col.var = "#2E9FDF", # Variables color
#                col.ind = "#696969" ,labelsize = 5 # Individuals color
#                )
#
```

```{r}
fviz_pca_ind(data.pca,
             title = "PCA Coloured by Permeability Group in Both Dataset,PC1 vs PC2",
             xlab = 'PC1 (50.6%)', ylab='PC2(23.7%)',
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = data_all$Per_Class, # color by groups
             palette = c("Green", "Red", "Blue"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )
```

```{r}

fviz_pca_ind(data.pca,
             axes = c(1, 3), # specify PC1 and PC3
             title = "PCA Coloured by Permeability Group in Both Dataset,PC1 vs PC3 ",
             xlab = 'PC1 (50.6%)', ylab='PC3 (10.1%)',
             geom.ind = "point", 
             col.ind = data_all$Per_Class, # color by groups
             palette = c("Green", "Red", "Blue"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )
```

```{r}
fviz_pca_ind(data.pca,
             title = "PCA Coloured by Peptidic Ratio Group in Both Dataset,PC1 vs PC2 ",
             xlab = 'PC1 (50.6%)', ylab='PC2(23.7%)',
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = data_all$Peptidic_Type, # color by groups
             palette = c("Green", "RED", "Blue"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )

```

```{r}

fviz_pca_ind(data.pca,
             axes = c(1, 3), # specify PC1 and PC3
             title = "PCA Coloured by Peptidic Ratio Group in Both Dataset,PC1 vs PC3",
             xlab = 'PC1 (50.6%)', ylab='PC3 (10.1%)',
             geom.ind = "point", 
             col.ind = data_all$Peptidic_Type, # color by groups
             palette = c('Green', "Red", "Blue"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )
```

## t-SNE

```{r}
library(Rtsne)
set.seed(101) # for reproducibility
```

```{r}
## Plot using ggplot2
#tsne_results_1 <- Rtsne(data_app[, -which(names(data_app) == "Per_Class","Peptidic_Type")], #perplexity = 30, theta = 0.0, dims = 2)
## Create a data frame for plotting
#tsne_data_1 <- data.frame(X = tsne_results_1$Y[,1], Y = tsne_results_1$Y[,2], Group = #data_app$Per_Class)
#
#ggplot(tsne_data_1, aes(x = X, y = Y, color = Group)) +
#  geom_point() +
#  ggtitle("t-SNE of Each Permeability Group, Papp") +
#  xlab("t-SNE Dimension 1") + ylab("t-SNE Dimension 2") +
#  scale_color_manual(values = c("Green", "Red", "Blue")) +
#  theme_minimal() +
#  labs(color = "Groups")
```

```{r}
#tsne_results_2 <-  Rtsne(data_app[, -which(names(data_app) == "Per_Class","Peptidic_Type")], #perplexity = 30, theta = 0.0, dims = 2)
## Create a data frame for plotting
#tsne_data_2 <- data.frame(X = tsne_results_2$Y[,1], Y = tsne_results_2$Y[,2], Group = #data_app$Peptidic_Type)
#
## Plot using ggplot2
#ggplot(tsne_data_2, aes(x = X, y = Y, color = Group)) +
#  geom_point() +
#  ggtitle("t-SNE of Each Peptidic Group, Papp") +
#  xlab("t-SNE Dimension 1") + ylab("t-SNE Dimension 2") +
#  scale_color_manual(values = c("Green", "Red", "Blue")) +
#  theme_minimal() +
#  labs(color = "Groups")
```

```{r}
tsne_results <- Rtsne(data_eff[, -which(names(data_eff) == "Peptidic_Type","Per_Class")], perplexity = 30, theta = 0.0, dims = 2)
# Create a data frame for plotting
tsne_data <- data.frame(X = tsne_results$Y[,1], Y = tsne_results$Y[,2], Group = data_eff$Peptidic_Type)

# Plot using ggplot2
ggplot(tsne_data, aes(x = X, y = Y, color = Group)) +
  geom_point() +
  ggtitle("t-SNE of Each Peptidic Group, Peff") +
  xlab("t-SNE Dimension 1") + ylab("t-SNE Dimension 2") +
  scale_color_manual(values = c("Green", "Blue")) +
  theme_minimal() +
  labs(color = "Groups")
```

```{r}
tsne_results <- Rtsne(data_eff[, -which(names(data_eff) == "Per_Class","Peptidic_Type")], perplexity = 30, theta = 0.0, dims = 2)
# Create a data frame for plotting
tsne_data <- data.frame(X = tsne_results$Y[,1], Y = tsne_results$Y[,2], Group = data_eff$Per_Class)

ggplot(tsne_data, aes(x = X, y = Y, color = Group)) +
  geom_point() +
  ggtitle("t-SNE of Each Permeability Group,Peff") +
  xlab("t-SNE Dimension 1") + ylab("t-SNE Dimension 2") +
  scale_color_manual(values = c("Green", "Red", "Blue")) +
  theme_minimal() +
  labs(color = "Groups")
```

```{r}
tsne_results <- Rtsne(data_app[, -which(names(data_app) == "Per_Class","Peptidic_Type")], perplexity = 30, theta = 0.0, dims = 2)
# Create a data frame for plotting
tsne_data <- data.frame(X = tsne_results$Y[,1], Y = tsne_results$Y[,2], Group = data_app$Per_Class)

ggplot(tsne_data, aes(x = X, y = Y, color = Group)) +
  geom_point() +
  ggtitle("t-SNE of Each Permeability Group,Papp") +
  xlab("t-SNE Dimension 1") + ylab("t-SNE Dimension 2") +
  scale_color_manual(values = c("Green", "Red", "Blue")) +
  theme_minimal() +
  labs(color = "Groups")
```

```{r}
tsne_results <- Rtsne(data_app[, -which(names(data_app) == "Peptidic_Type","Per_Class")], perplexity = 30, theta = 0.0, dims = 2)
# Create a data frame for plotting
tsne_data <- data.frame(X = tsne_results$Y[,1], Y = tsne_results$Y[,2], Group = data_app$Peptidic_Type)

# Plot using ggplot2
ggplot(tsne_data, aes(x = X, y = Y, color = Group)) +
  geom_point() +
  ggtitle("t-SNE of Each Peptidic Group, Papp") +
  xlab("t-SNE Dimension 1") + ylab("t-SNE Dimension 2") +
  scale_color_manual(values = c("Green", "Blue","Red")) +
  theme_minimal() +
  labs(color = "Groups")
```

## PCA for Papp Dataset Only
```{r}
app_normalized <- scale(data_app_features)
head(app_normalized)
corr_matrix_app <- cor(app_normalized)
ggcorrplot(corr_matrix_app,
           title = "Corrlation of Features in Papp Dataset")
```
```{r}
data.pca_app <- PCA(data_app_features, graph = FALSE)
eig.val <- get_eigenvalue(data.pca_app)
fviz_eig(data.pca_app, title = "Scree Plot of Features in Papp Dataset",
         addlabels = TRUE, ylim = c(0, 60))

```
```{r}
fviz_pca_var(data.pca_app, 
             title = "PCA Loading Plots of Papp Dataset, PC1 vs PC2",
             xlab = 'PC1 (44.9%)', ylab='PC2(23.9%)',
             col.var = "purple",
             labelsize = 3
             )
```

```{r}
fviz_pca_var(data.pca_app, 
            axes = c(1, 3), # specify PC1 and PC3
             title = "PCA Loading Plots of Papp Dataset, PC1 vs PC3",
             xlab = 'PC1 (44.9%)', ylab='PC3 (12.6%)',
             col.var = "Purple",
             labelsize = 3)
```

```{r}
fviz_pca_biplot(data.pca_app,
             title = "PCA Coloured by Permeability Group in Papp Dataset,PC1 vs PC2",
             xlab = 'PC1 (44.9%)', ylab='PC2(23.9%)',
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = data_app$Per_Class, # color by groups
             palette = c("Green", "Red", "Blue"),
             addEllipses = F, # Concentration ellipses
             legend.title = "Groups",
             col.var = "gra"
             )
```

```{r}
fviz_pca_ind(data.pca_app,
             axes = c(1, 3), # specify PC1 and PC3
             title = "PCA Coloured by Permeability Group in Papp Dataset,PC1 vs PC3 ",
             xlab = 'PC1 (44.9%)', ylab='PC3 (12.6%)',
             geom.ind = "point", 
             col.ind = data_app$Per_Class, # color by groups
             palette = c("Green", "Red", "Blue"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )
```

```{r}
fviz_pca_ind(data.pca_app,
             title = "PCA Coloured by Peptidic Group in Papp Dataset,PC1 vs PC2",
             xlab = 'PC1 (44.9%)', ylab='PC2(23.9%)',
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = data_app$Peptidic_Type, # color by groups
             palette = c("Green", "Red", "Blue"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )
```

```{r}
fviz_pca_ind(data.pca_app,
             axes = c(1, 3), # specify PC1 and PC3
             title = "PCA Coloured by Peptidic Group in Papp Dataset,PC1 vs PC3 ",
             xlab = 'PC1 (44.9%)', ylab='PC3 (12.6%)',
             geom.ind = "point", 
             col.ind = data_app$Peptidic_Type, # color by groups
             palette = c("Green", "Red", "Blue"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )
```
## PCA of Peff ONLY
```{r}
eff_normalized <- scale(data_eff_features)
head(eff_normalized)
corr_matrix_eff <- cor(eff_normalized)
ggcorrplot(corr_matrix_eff,
           title = "Corrlation of Features in Peff Dataset")
```

```{r}
data.pca_eff <- PCA(data_eff_features, graph = FALSE)
eig.val <- get_eigenvalue(data.pca_eff)
fviz_eig(data.pca_eff, title = "Scree Plot of Features in Peff Dataset",
         addlabels = TRUE, ylim = c(0, 70))

```
```{r}
fviz_pca_var(data.pca_eff, 
             title = "PCA Loading Plots of Peff Dataset, PC1 vs PC2",
             xlab = 'PC1 (66.0%)', ylab='PC2(21.0%)',
             col.var = "purple",
             labelsize = 3
             )
```

```{r}
fviz_pca_var(data.pca_eff, 
            axes = c(1, 3), # specify PC1 and PC3
             title = "PCA Loading Plots of Peff Dataset, PC1 vs PC3",
             xlab = 'PC1 (66.0%)', ylab='PC3 (7.1%)',
             col.var = "Purple",
             labelsize = 3)
```

```{r}
fviz_pca_ind(data.pca_eff,
             title = "PCA Coloured by Permeability Group in Peff Dataset,PC1 vs PC2",
             xlab = 'PC1 (61.0%)', ylab='PC2(21.0%)',
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = data_eff$Per_Class, # color by groups
             palette = c("Green", "Red", "Blue"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )
```

```{r}
fviz_pca_ind(data.pca_eff,
             axes = c(1, 3), # specify PC1 and PC3
             title = "PCA Coloured by Permeability Group in Peff Dataset,PC1 vs PC3 ",
             xlab = 'PC1 (61.0%)', ylab='PC3 (7.1%)',
             geom.ind = "point", 
             col.ind = data_eff$Per_Class, # color by groups
             palette = c("Green", "Red", "Blue"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )
```

```{r}
fviz_pca_ind(data.pca_eff,
             title = "PCA Coloured by Peptidic Group in Peff Dataset,PC1 vs PC2",
             xlab = 'PC1 (61.0%)', ylab='PC2(21.0%)',
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = data_eff$Peptidic_Type, # color by groups
             palette = c("Green", "Blue"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )
```

```{r}
fviz_pca_ind(data.pca_eff,
             axes = c(1, 3), # specify PC1 and PC3
             title = "PCA Coloured by Peptidic Group in Peff Dataset,PC1 vs PC3 ",
             xlab = 'PC1 (61.0%)', ylab='PC3 (7.1%)',
             geom.ind = "point", 
             col.ind = data_eff$Peptidic_Type, # color by groups
             palette = c("Green", "Blue"),
             addEllipses = TRUE, # Concentration ellipses
             legend.title = "Groups"
             )
```




