# Generated by Django 3.2.23 on 2024-02-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='macrocycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('smiles', models.CharField(max_length=255)),
                ('Original_ID', models.CharField(max_length=255)),
                ('Standardise_SMILES', models.CharField(max_length=255)),
                ('Value', models.CharField(max_length=255)),
                ('No_symbol_Value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Unit', models.CharField(max_length=255)),
                ('Endpoint', models.CharField(max_length=255)),
                ('Standardized_Value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Standardized_Endpoint', models.CharField(max_length=255)),
                ('Assay', models.CharField(max_length=255)),
                ('Link', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Source', models.CharField(max_length=255)),
                ('Publish_Year', models.CharField(max_length=255)),
                ('Macrocycle_Ring_Size', models.IntegerField()),
                ('Macrocycle_Free_Amide_Count', models.IntegerField()),
                ('Macrocycle_Substituted_Amide_Count', models.IntegerField()),
                ('Macrocycle_Overall_Amide_Count', models.IntegerField()),
                ('Macrocycle_Core_smiles', models.CharField(max_length=255)),
                ('Macrocycle_Peripheral_smiles', models.CharField(max_length=255)),
                ('Macrocycle_Free_Amide_Ratio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Peptidic_Type', models.CharField(max_length=255)),
                ('Macrocycle_Overall_Amide_Ratio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Num_Rings', models.IntegerField()),
                ('Num_Aromatic_Rings', models.IntegerField()),
                ('cLogP', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Molecular_Weight', models.DecimalField(decimal_places=1, max_digits=10)),
                ('Num_H_Acceptors', models.IntegerField()),
                ('Num_H_Donors', models.IntegerField()),
                ('Num_Heavy_Atoms', models.IntegerField()),
                ('Num_Carbon_Atoms', models.IntegerField()),
                ('Fraction_SP3_Carbons', models.DecimalField(decimal_places=3, max_digits=10)),
                ('TPSA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Num_Rotatable_Bonds', models.IntegerField()),
                ('Num_Charged_Atoms', models.IntegerField()),
                ('Net_Charge', models.IntegerField()),
                ('Kier_index', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
