# Generated by Django 3.2.23 on 2024-03-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macrodb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrocycle',
            name='InchiKey',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
