# Generated by Django 3.2.23 on 2024-04-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macrodb', '0002_macrocycle_inchikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrocycle',
            name='Citation',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='macrocycle',
            name='Common_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='macrocycle',
            name='Fraction_SP3_Carbons',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='macrocycle',
            name='Kier_index',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='macrocycle',
            name='Macrocycle_Free_Amide_Ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='macrocycle',
            name='Macrocycle_Overall_Amide_Ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='macrocycle',
            name='Molecular_Weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='macrocycle',
            name='No_symbol_Value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='macrocycle',
            name='Standardized_Value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='macrocycle',
            name='cLogP',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
