# Generated by Django 3.2.23 on 2024-09-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macrodb', '0006_rename_macrocycle_core_smiles_macrocycle_macrocycle_ring_smiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrocycle',
            name='CAS_no',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
