# Generated by Django 3.2.23 on 2024-10-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macrodb', '0007_macrocycle_cas_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macrocycle',
            name='CAS_no',
        ),
    ]
